# ---- Platform detection ----------------------------------------------------
# Windows (MSYS2/MinGW) sets OS=Windows_NT; otherwise ask uname.
UNAME_S := $(shell uname -s 2>/dev/null)
UNAME_M := $(shell uname -m 2>/dev/null)

ifeq ($(OS),Windows_NT)
    PLATFORM := windows
else ifeq ($(UNAME_S),Darwin)
    PLATFORM := macos
else
    PLATFORM := linux
endif

# ---- Project layout --------------------------------------------------------
SRC_DIR   := src
INC_DIR   := include
BUILD_DIR := build
OBJ_DIR   := $(BUILD_DIR)/obj

SRCS := $(SRC_DIR)/main.cpp $(SRC_DIR)/NeuralNetwork_CPU.cpp
OBJS := $(SRCS:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)
DEPS := $(OBJS:.o=.d)

# ---- Common flags ----------------------------------------------------------
CXXFLAGS := -std=c++17 -O3 -Wall -Wextra -I$(INC_DIR) -MMD -MP -DNDEBUG
LDFLAGS  :=
LDLIBS   := -lz -lm

# raylib via pkg-config (brew / apt / pacman / MSYS2 all ship raylib.pc)
CXXFLAGS += $(shell pkg-config --cflags raylib 2>/dev/null)
LDLIBS   += $(shell pkg-config --libs raylib 2>/dev/null)

# ---- Per-platform settings -------------------------------------------------
ifeq ($(PLATFORM),macos)
    ifeq ($(origin CXX),default)
        CXX := clang++
    endif
    # Apple clang needs libomp from Homebrew:  brew install libomp
    LIBOMP_PREFIX := $(shell brew --prefix libomp 2>/dev/null)
    CXXFLAGS += -Xpreprocessor -fopenmp -I$(LIBOMP_PREFIX)/include
    LDFLAGS  += -L$(LIBOMP_PREFIX)/lib
    LDLIBS   += -lomp
    ifeq ($(UNAME_M),arm64)
        CXXFLAGS += -mcpu=apple-m1
    else
        CXXFLAGS += -march=native
    endif
    EXE :=
endif

ifeq ($(PLATFORM),linux)
    ifeq ($(origin CXX),default)
        CXX := g++
    endif
    CXXFLAGS += -fopenmp -march=native
    LDFLAGS  += -fopenmp
    EXE :=
endif

ifeq ($(PLATFORM),windows)
    # Intended for MSYS2 (MinGW64 shell) with: mingw-w64-x86_64-{gcc,raylib,zlib,pkgconf}
    ifeq ($(origin CXX),default)
        CXX := g++
    endif
    CXXFLAGS += -fopenmp -march=native
    LDFLAGS  += -fopenmp
    EXE := .exe
endif

TARGET := $(BUILD_DIR)/nn$(EXE)

# ---- Targets ---------------------------------------------------------------
.PHONY: all run clean info

all: $(TARGET)

$(TARGET): $(OBJS) | $(BUILD_DIR)
	$(CXX) $(OBJS) -o $@ $(LDFLAGS) $(LDLIBS)

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp | $(OBJ_DIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(BUILD_DIR) $(OBJ_DIR):
	mkdir -p $@

# Run from the project root so the relative data/ paths resolve
run: $(TARGET)
	./$(TARGET)

clean:
	rm -rf $(BUILD_DIR)

info:
	@echo "Platform: $(PLATFORM)"
	@echo "CXX:      $(CXX)"
	@echo "CXXFLAGS: $(CXXFLAGS)"
	@echo "LDFLAGS:  $(LDFLAGS)"
	@echo "LDLIBS:   $(LDLIBS)"

# Header dependency files generated by -MMD
-include $(DEPS)